<a href="https://colab.research.google.com/github/pujitha9908/Pujitha-/blob/main/colab_basic_and_python_codes_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!cat /proc/cpuinfo

#no need exclamatory for ruuning python programs
#tells the details of cpu

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2200.220
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi
bogomips	: 4400.44
clflush size	: 64
cache_alignment	: 64
ad

In [ ]:
! cat  /proc/meminfo

MemTotal:       13290452 kB
MemFree:         9154732 kB
MemAvailable:   12163928 kB
Buffers:          115580 kB
Cached:          3055700 kB
SwapCached:            0 kB
Active:           790788 kB
Inactive:        3047936 kB
Active(anon):       1448 kB
Inactive(anon):   667796 kB
Active(file):     789340 kB
Inactive(file):  2380140 kB
Unevictable:           8 kB
Mlocked:               8 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:              3200 kB
Writeback:             0 kB
AnonPages:        667540 kB
Mapped:           324540 kB
Shmem:              1792 kB
KReclaimable:     161632 kB
Slab:             203108 kB
SReclaimable:     161632 kB
SUnreclaim:        41476 kB
KernelStack:        5908 kB
PageTables:        11156 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6645224 kB
Committed_AS:    3024100 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       12264 kB
VmallocChunk:    

installing libraries


In [ ]:
pip install pandas

programming language used for machine learning

1.python
2.R
# printfunction

In [ ]:
print("machine learning")

machine learning


In [ ]:
print("machine learning" + "projects")

machine learningprojects


In [ ]:
print(8)

8


In [ ]:
print(8+8)

16


# Basic data types
1. int
2.float
3.string

In [ ]:
# string data type
a="pujitha"
print(a)
type(a)

pujitha


str

In [ ]:
#interger datatype
a=10
print(a)
type(a)

10


int

In [ ]:
#float data type
a=0.004
print(a)
type(a)

0.004


float

#constanta and variables

In [ ]:
# constants
supervariable = "pujitha chowdary"
print(supervariable)

krishna


In [ ]:
supervariable = "krishna"
print(supervariable)

krishna


In [ ]:
# variables
hero1,hero2,hero3 = "thor","ironman","hulk"
print(hero1)
print(hero2)
print(hero3)
#mutplie variables
x=y=z = 100
print(x)
print(y)
print(z)

thor
ironman
hulk
100
100
100


#input function

In [ ]:
# here input reads as integer
number_1=int(input("enter the first number"))
number_2=int(input("enter the second number"))
print(number_1+number_2)

# here input reads as a string
number_1=input("enter the first number")
number_2=input("enter the second number")
sum= number_1+number_2
print(sum)


enter the first number8
enter the second number9
17


In [ ]:
# changing the data type in python
a=5
b=float(a)
print(b)
type(b)

c="8886"
d=int(c)
print(c)
print(d)
print(d)
print(type(c))
type(d)

5.0
8886
8886
8886
<class 'str'>


int

# basic data types of python
1.integer
2.floating point
3.complex
4.boolean
5.string

In [ ]:
#interger data type
a = 8
print(a)
type(a)

8


int

In [ ]:
#floating point
b=8.8
print(b)
type(b)

8.8


float

In [ ]:
#complex numbers
c=1+3j
print(c)
type(c)

(1+3j)


complex

# conversion of one data type to another

In [ ]:

# conversion of integer to float
x=88
print(x)
print(type(x))
y=float(x)
print(y)
print(type(y))

88
<class 'int'>
88.0
<class 'float'>


In [ ]:
# conversion of float to integer
x=8.8
print(x)
print(type(x))
y=int(x)
print(y)
print(type(y))

8.8
<class 'float'>
8
<class 'int'>


# Boolean data type
1. true
2.false

In [ ]:
a=True
print(a)
type(a)

True


bool

In [ ]:
a=False
print(a)
type(a)

False


bool

In [ ]:
a = 3<7
print(a)
type(a)

True


bool

In [ ]:
a = 3<7
print(a)
type(a)

True


bool

#string

In [ ]:
print("machine learning")

machine learning


In [ ]:
my_string = "pujitha"
print(my_string)
type(my_string)

pujitha


str

In [ ]:
print("hello"*5)

hellohellohellohellohello


#Slicing

In [ ]:
# values from index 1 to 5-1 will be sliced
my_string="puchuu"
print(my_string[0:2])

pu


In [ ]:
#values from right side will be in negative print from -1 ,[-5:-1]
my_string="puchuuuuu"
print(my_string[:-1])
print(my_string[-6:-1])

puchuuuu
huuuu


In [ ]:
# step
print(my_string[0:9:2])

pcuuu


# string concatenation

In [ ]:
word_1 = 'machine'
word_2 = 'learning'
print(word_1 + word_2)

machinelearning


#Types of objects in python
1.immutable objects
2.mutable objects

Immutable objects
1.int
2.float
3.string
4.bool
5.tuple
6.boolean

Mutable objects
1.list
1.set
3.dictionary

#list
list can store mutliple data types


In [ ]:
#list should be included in the square
my_list=[1,2,3,4,5]
print(my_list)
type(my_list)

[1, 2, 3, 4, 5]


list

In [ ]:
my_list=[1,2,3,4,'pujitha',True]
print(my_list)
type(my_list)



[1, 2, 3, 4, 'pujitha', True]


#Lists are mutable - changegable
lists Allows duplicates
Operations on list
1.append()
2.delete()
3.clear()
4.copy()
5.count()
6.reverse()
7.sort()
8.indexing()
9.len()

In [ ]:
#add elements to a list
a=['pujiha',5,5,8,0.9,True]
a.append("krishna")
print(a)


['pujiha', 5, 8, 0.9, True, 'krishna']


In [ ]:
# print elements of a list using their index
a=['pujiha',5,8,0.9,True]
print(a[0])
print(a[2])


pujiha
8


In [ ]:
#list allows duplicate values
a=['pujiha',5,5,8,0.9,True]
print(a)

['pujiha', 5, 5, 8, 0.9, True]


In [ ]:
#length of a list
a=['pujiha',5,5,8,0.9,True]
b=['pujitha']
print(len(a))
print(len(b))

6
1


In [ ]:
#initiating an empty list
list_1=[]
print(list_1)
type(list_1)

[]


list

In [ ]:
list_1=[]
list_1.append(1)
print(list_1)
type(list_1)

[1]


list

In [ ]:
#delete an element in the list
a = ['pujitha',5,6,'krishna',0.9]
print(a)
del a[2]
print(a)


['pujitha', 5, 6, 'krishna', 0.9]
['pujitha', 5, 'krishna', 0.9]


In [ ]:
#pop the element in the list
b=a.pop(0)
print(a)
print(b)

[5, 0.9]
pujitha


In [ ]:
# join two lists
list_2=[1,'vijaya lakshmi',3,4]
list_3=[5,6,'krishna',8]
print(list_2+list_3)

[1, 'vijaya lakshmi', 3, 4, 5, 6, 'krishna', 8]


# Tuple
1.tuples are in round brackets
2. tuples are used to store mutliple items in single variable
3.tuple items are odered ,unchangeable and allow duplicate values
4. tuple items are in indexing from 0


Operations on tuple
1.count()
2.indexing()
3.len()
4.join()


In [ ]:
a = (1,2,3,4,5)
print(a)
type(a)

(1, 2, 3, 4, 5)


tuple

In [ ]:
# join the two tuples
tuple_1=(1,2,3,4,5)
tuple_2=(6,7,8,9,10)
tuple_3=(tuple_1,tuple_2)
print(tuple_3)

((1, 2, 3, 4, 5), (6, 7, 8, 9, 10))


In [ ]:
#tuple allows mutliple data types
tuple=(1,'vijayalakshmi','krishna',7,0.9,True)
print(tuple)
type(tuple)

(1, 'vijayalakshmi', 'krishna', 7, 0.9, True)


tuple

In [ ]:
#converting a list to a tuple

#Set
1. sets are wriiten curly brackets
2.unordred,unindexeing ,unchangeable,dont allow duplicates

In [ ]:
my_set={1,2,3,4,5}
print(my_set)
type(my_set)

{1, 2, 3, 4, 5}


set

In [ ]:
print(my_set[0])

TypeError: 'set' object is not subscriptable

In [ ]:
# convert a list in to a set
my_list=[1,2,3,4,5]
print(my_list)
type(my_list)
my_set=set(my_list)
print(my_set)
type(my_set)

[1, 2, 3, 4, 5]
{1, 2, 3, 4, 5}


set

In [ ]:
# set does not duplicate values
set_1={1,2,3,4,5,1,2,3,4,5}
print(set_1)

{1, 2, 3, 4, 5}


#Dictionaries
1.used to store data values in key values pairs
2. ordered , changeable and not allow duplicates
3. dictionaries are written in curly brackets and have keys and values

In [ ]:
# key-value pair
my_dict={'name':'pujitha',2 :20,3 :'india'}
print(my_dict)
type(my_dict)

{'name': 'pujitha', 2: 20, 3: 'india'}


dict

In [ ]:
#change or update value
my_dict['age']=21
print(my_dict)

{'name': 'pujitha', 2: 20, 3: 'india', 'age': 21}


In [ ]:
my_dict['name']="krishna"
print(my_dict)

{'name': 'krishna', 2: 20, 3: 'india', 'age': 21}


In [ ]:
#deleting of an element
del my_dict[3]
print(my_dict)

{'name': 'krishna', 2: 20, 'age': 21}


In [ ]:
my_dict.pop(2)
print(my_dict)

{'name': 'krishna', 'age': 21}


In [ ]:
my_dict.clear()
print(my_dict)

{}


#Operators in python:
1. Arithemetic
2.Assignment
3.comparison
4.logical
5.identify
6.membership


# 1. Arithmetic operators

In [ ]:
a = 9
b = 10
print(a+b) #add
print(a-b) #sub
print(a*b) #multipication
print(a/b) #division(quotient)
print(a//b) # floor division
print(a%b) #remainder

19
-1
90
0.9
0
9


# 2.Assignment operators

1.+=
2.-=
3.*=
4.**=
5./=
6.%=

In [ ]:
a=5
print(a)

5


In [ ]:
a=5
a+=5 #a=a+5
print(a)

10


In [ ]:
b=5
c=5
b -=2 # b=b-2
c*=2 #c=c*5
print(b)
print(c)

3
10


# 3. Comparison operators

 ==	Equal	x == y
 !=	Not equal	x != y
 >	Greater than	x > y
 <	Less than	x < y
 >= Greater than or equal to	x >= y
 <=	Less than or equal to	x <= y

In [ ]:
a=15
b=10
print(a==b)
print(a!=b)
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)


False
True
True
False
True
False


# 4.Logical operators

(and)
	Returns True if both statements are true	x < 5 and  x < 10
(or)
  Returns True if one of the statements is true	x < 5 or x < 4
(not)
	Reverse the result, returns False if the result is true	not(x < 5 and x < 10

In [ ]:
x = 5

print(x > 3 and x < 10)

print(x > 3 or x < 4)

print(not(x > 3 and x < 10))

True
True
False


# 5.Identity Operators

(is)
  Returns True if both variables are the same object	x is y
(is not)
	Returns True if both variables are not the same object	x is not y

In [ ]:
x = ["apple", "banana"]
y = ["apple", "banana"]
z = x

print(x is z)

print(x is y)

print(x == y)

True
False
True


In [ ]:
x = ["apple", "banana"]
y = ["apple", "banana"]
z = x

print(x is not z)

print(x is not y)

print(x != y)


False
True
False


# 6.membership operations
1.(in)
 	 Returns True if a sequence with the specified value is present in the object
   x in y
2.(not in)
	Returns True if a sequence with the specified value is not present in the object
  **x not in y**

In [ ]:
x = ["apple", "banana"]

print("banana" in x)



True


In [ ]:
x = ["apple", "banana"]

print("pineapple" not in x)


True


# if-else statement

The if-else statement is used to execute both the true part and the false part of a given condition.

In [ ]:
def compare_numbers():
    # Get user inputs
    a = int(input("Enter the first number (a): "))
    b = int(input("Enter the second number (b): "))

    # Compare the numbers
    if b > a:
        print("b is greater than a")
    else:
        print("a is greater than b")

# Call the function
compare_numbers()


Enter the first number (a): 9
Enter the second number (b): 6
a is greater than b


# Elif-condition

The elif keyword is Python's way of saying "if the previous conditions were not true, then try this condition".

In [ ]:
a = 33
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

a and b are equal


In [ ]:
# Define the calculator functions
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b != 0:
        return a / b
    else:
        return "Error: Division by zero is not allowed."

# Main calculator function
def calculator():
    print("Welcome to the Calculator Program!")
    print("Choose an operation:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")

    choice = input("Enter the number corresponding to your choice (1/2/3/4): ")

    # Check for valid input
    if choice in ['1', '2', '3', '4']:
        num1 = float(input("Enter the first number: "))
        num2 = float(input("Enter the second number: "))

        if choice == '1':
            result = add(num1, num2)
            print(f"The result of addition is: {result}")
        elif choice == '2':
            result = subtract(num1, num2)
            print(f"The result of subtraction is: {result}")
        elif choice == '3':
            result = multiply(num1, num2)
            print(f"The result of multiplication is: {result}")
        elif choice == '4':
            result = divide(num1, num2)
            print(f"The result of division is: {result}")
    else:
        print("Invalid input! Please choose a valid operation.")

# Run the calculator
calculator()


Welcome to the Calculator Program!
Choose an operation:
1. Addition
2. Subtraction
3. Multiplication
4. Division
Enter the number corresponding to your choice (1/2/3/4): 2
Enter the first number: 5
Enter the second number: 5
The result of subtraction is: 0.0


#Nested If
You can have if statements inside if statements, this is called nested if statements.

In [ ]:
x = int(input("enter a number : "))

if x > 10:
  print("Above ten,")
  if x > 20:
    print("and also above 20!")
  else:
    print("but not above 20.")

enter a number : 24
Above ten,
and also above 20!


#Loops
A for loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string).


In [ ]:
#print each fruit in a fruit list:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

apple
banana
cherry


In [ ]:
#Loop through the letters in the word "banana":
for x in "banana":
  print(x)

b
a
n
a
n
a


#Range function
The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and ends at a specified number.


In [ ]:
for x in range(6):
  print(x)

0
1
2
3
4
5


In [ ]:
#Increment the sequence with 3 (default is 1):
for x in range(2, 30, 3):#start=2 , end=30  step=3
  print(x)

2
5
8
11
14
17
20
23
26
29


In [ ]:
#The else keyword in a for loop specifies a block of code to be executed when the loop is finished:
for x in range(6):
  print(x)
else:
  print("Finally finished!")

0
1
2
3
4
5
Finally finished!


#Nested loops
A nested loop is a loop inside a loop.

The "inner loop" will be executed one time for each iteration of the "outer loop":

In [ ]:
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y)

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry


#While loops
With the while loop we can execute a set of statements as long as a condition is true.

In [ ]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


#The continue Statement
With the continue statement we can stop the current iteration, and continue with the next:



In [ ]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    continue
  print(i)

1
2
4
5
6


#The break Statement
With the break statement we can stop the loop even if the while condition is true:

In [ ]:
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1

1
2
3


#The else Statement
With the else statement we can run a block of code once when the condition no longer is true:

In [ ]:
i = 1
while i < 6:
  print(i)
  i += 1
else:
  print("i is no longer less than 6")

1
2
3
4
5
i is no longer less than 6


#Functions
A function is a block of code which only runs when it is called.

In [ ]:
#Creating a Function
def my_function():
  print("Hello from a function")


# factorial of a number
factorial of 5 = 5*4*3*2*1=120


In [ ]:
num=int(input("enter a number : "))
factorial=1
if num<0:
  print("factorial does not exist for negative numbers")
elif num==0:
    print("the factorial of 0 is 1")
else:
    for i in range(1,num+1):
        factorial=factorial*i
        print("the factorial of",num,"is",factorial)

enter a number : 5
the factorial of 5 is 1
the factorial of 5 is 2
the factorial of 5 is 6
the factorial of 5 is 24
the factorial of 5 is 120


In [ ]:
def factorial_value(num):
   factorial=1

   if num<0:
       return"factorial does not exist for negative numbers"
   elif num==0:
        return"the factorial of 0 is 1"
   else:
        for i in range(1,num+1):
            factorial=factorial*i
        return factorial
num=int(input("enter a number : "))
print(factorial_value(num))

enter a number : 6
720


In [ ]:
print(factorial_value(6))

720


#function arguments
1.Information can be passed into functions as arguments.

2. Arguments are specified after the function name, inside the parentheses. You can add as many arguments as you want, just separate them with a comma.

In [ ]:
def my_function(fname):
  print(fname + " Refsnes")

my_function("Emil")
my_function("Tobias")
my_function("Linus")

Emil Refsnes
Tobias Refsnes
Linus Refsnes


#Num py - numerical python
advantages of numpu arrays
1.allows several mathematical operations
2.faster operations

In [ ]:
import numpy as np

In [ ]:
from time import process_time

In [ ]:
python_list=[i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time =process_time()

print (end_time - start_time)

0.0009230180000017185


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time=process_time()

np_array +=5

end_time=process_time()

print(end_time-start_time)

0.0014941069999991896


In [ ]:
#create a list
list=[1,2,3,4,5]
print(list)
type(list)

[1, 2, 3, 4, 5]


list

In [ ]:
#create a list using a nump py
a=np.array([1,2,3,4,5])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
a.shape

(5,)

In [ ]:
#creating a two dimensional array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

#  intial place holders in numpy arrays

In [ ]:
#create a numpy array of zeros
import numpy as np
c=np.zeros((4,5))
print(c)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy array of ones
d=np.ones((3,3),dtype=float)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
e =np.full((5,4),7)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# create an identity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# create a numpy with a random values
b=np.random.random((3,4))
print(b)

[[0.6673551  0.33372625 0.76277194 0.18759532]
 [0.84059203 0.60921761 0.938133   0.5509714 ]
 [0.89105108 0.06423096 0.90931357 0.01565892]]


In [ ]:
# create a numpy with a random integer values
c=np.random.randint(10,100,(3,5))  #randint means integers
print(c)

[[73 10 79 97 59]
 [11 54 46 29 39]
 [24 96 64 82 41]]


In [ ]:
# array of evenly spaced values --->specifying the number of values required
c = np.linspace(10,30,5)
print(c)

# array of evenly spaced values --->specifying the step
c = np.arange(10,30,5)
print(c)

[10. 15. 20. 25. 30.]
[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list_2=[1,2,3,4,5,6]
np_array=np.array(list_2)
print(np_array)
type(np_array)

[1 2 3 4 5 6]


numpy.ndarray

# analysing a numpy array

In [ ]:
a = np.random.randint(10,90,(5,5))
print(a)

[[86 22 84 47 84]
 [59 78 59 58 77]
 [78 66 64 62 63]
 [23 12 70 21 71]
 [27 16 46 68 75]]


In [ ]:
#arrary dimension
a.shape

(5, 5)

In [ ]:
# number of dimensions
a.ndim

2

In [ ]:
# number of elements in the array
a.size

25

In [ ]:
# checking the data type of the values in the array
a.dtype

dtype('int64')

#Mathematical operations on a numpy

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatenate two stes

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a= np.random.randint(0,10,(3,3))
b= np.random.randint(10,20,(3,3))
print(a)
print(b)

[[7 3 9]
 [2 4 7]
 [1 0 1]]
[[14 14 12]
 [17 17 18]
 [17 19 18]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[21 17 21]
 [19 21 25]
 [18 19 19]]
[[ -7 -11  -3]
 [-15 -13 -11]
 [-16 -19 -17]]
[[ 98  42 108]
 [ 34  68 126]
 [ 17   0  18]]
[[0.5        0.21428571 0.75      ]
 [0.11764706 0.23529412 0.38888889]
 [0.05882353 0.         0.05555556]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[21 17 21]
 [19 21 25]
 [18 19 19]]
[[ -7 -11  -3]
 [-15 -13 -11]
 [-16 -19 -17]]
[[ 98  42 108]
 [ 34  68 126]
 [ 17   0  18]]
[[0.5        0.21428571 0.75      ]
 [0.11764706 0.23529412 0.38888889]
 [0.05882353 0.         0.05555556]]


#array manipulation

In [ ]:
array=np.random.randint(10,100,(2,3))
print(array)
print(array.shape)

[[99 12 44]
 [39 70 81]]
(2, 3)


In [ ]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[99 39]
 [12 70]
 [44 81]]
(3, 2)


In [ ]:
a = np.random.randint(0,10,(3,3))
b= a.T
print(a)
print(b)

[[3 4 6]
 [1 0 9]
 [9 6 5]]
[[3 1 9]
 [4 0 6]
 [6 9 5]]


In [ ]:
# reshaping a array
a=np.random.randint(0,10,(2,3))
b=a.reshape(3,2)
print(a)
print(b)

[[7 6 9]
 [3 1 9]]
[[7 6]
 [9 3]
 [1 9]]
